spring:
  application.name: proxysql

  docker:
    compose:
      lifecycle-management: start-and-stop
      file: ${projectRootDir}/compose.yml

  datasource:
    url: jdbc:mariadb://localhost:6033/mydatabase
    username: myuser
    password: secret

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    tutorials: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
