services:
  pgvector:
    image: pgvector/pgvector:pg18-trixie
    container_name: pgvector
    environment:
      POSTGRES_DB: tutorials-spring-ai
      POSTGRES_USER: tutorials
      POSTGRES_PASSWORD: tutorials
    ports:
      - "5432:5432"
    volumes:
      - ./docker/pgvector:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    depends_on:
      pgvector:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: tutorials@local.dev
      PGADMIN_DEFAULT_PASSWORD: tutorials
    ports:
      - "5050:80"
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
